<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\backend_menu;

class BackendMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
    	backend_menu::insert([
    		[
                'refid'             => 0,
                'sequence'          => 1,
                'menu_type'         => 5,
                'icon'              => 'analytics',
                'shortname'         => 'Dashboard',
                'caption'           => 'DASHBOARD',
                'action'            => '/dashboard',
                'show'              => '0',
                'create'            => '1',
                'update'            => '1',
                'suspend'           => '1',
                'delete'            => '1',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 0,
                'sequence'          => 2,
                'menu_type'         => 4,
                'icon'              => 'newspaper',
                'shortname'         => 'Website Content',
                'caption'           => 'WEBSITE CONTENT',
                'action'            => null,
                'show'              => '1',
                'create'            => '1',
                'update'            => '1',
                'suspend'           => '1',
                'delete'            => '1',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 2,
                'sequence'          => 1,
                'menu_type'         => 5,
                'icon'              => 'file_copy',
                'shortname'         => 'Halaman Wegsite',
                'caption'           => 'HALAMAN WEBSITE',
                'action'            => '/web-content/halaman-website',
                'show'              => '0',
                'create'            => '0',
                'update'            => '0',
                'suspend'           => '0',
                'delete'            => '0',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 2,
                'sequence'          => 2,
                'menu_type'         => 5,
                'icon'              => 'menu',
                'shortname'         => 'Wegsite Menu',
                'caption'           => 'WEBSITE MENU',
                'action'            => '/backend/website-menu',
                'show'              => '0',
                'create'            => '0',
                'update'            => '0',
                'suspend'           => '0',
                'delete'            => '0',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 0,
                'sequence'          => 3,
                'menu_type'         => 4,
                'icon'              => 'edit_document',
                'shortname'         => 'Content Management',
                'caption'           => 'CONTENT MANAGEMENT',
                'action'            => null,
                'show'              => '1',
                'create'            => '1',
                'update'            => '1',
                'suspend'           => '1',
                'delete'            => '1',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 5,
                'sequence'          => 2,
                'menu_type'         => 5,
                'icon'              => 'photo_library',
                'shortname'         => 'Image Slider',
                'caption'           => 'IMAGE SLIDER',
                'action'            => '/backend/image-slider',
                'show'              => '0',
                'create'            => '0',
                'update'            => '0',
                'suspend'           => '0',
                'delete'            => '0',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 5,
                'sequence'          => 1,
                'menu_type'         => 5,
                'icon'              => 'newspaper',
                'shortname'         => 'Posting Berita',
                'caption'           => 'POSTING BERITA',
                'action'            => '/backend/posting-berita',
                'show'              => '0',
                'create'            => '0',
                'update'            => '0',
                'suspend'           => '0',
                'delete'            => '0',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 5,
                'sequence'          => 3,
                'menu_type'         => 5,
                'icon'              => 'info',
                'shortname'         => 'Informasi Penting',
                'caption'           => 'INFORMASI PENTING',
                'action'            => '/backend/informasi-penting',
                'show'              => '0',
                'create'            => '0',
                'update'            => '0',
                'suspend'           => '0',
                'delete'            => '0',
                'showMenu'          => '0',
                'status'            => '2',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 5,
                'sequence'          => 4,
                'menu_type'         => 5,
                'icon'              => 'add_link',
                'shortname'         => 'Link Terkait',
                'caption'           => 'LINK TERKAIT',
                'action'            => '/backend/link-terkait',
                'show'              => '0',
                'create'            => '0',
                'update'            => '0',
                'suspend'           => '0',
                'delete'            => '0',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 5,
                'sequence'          => 5,
                'menu_type'         => 5,
                'icon'              => 'folder_open',
                'shortname'         => 'File Management',
                'caption'           => 'FILE MANAGEMENT',
                'action'            => '/content-management/file-management',
                'show'              => '0',
                'create'            => '0',
                'update'            => '0',
                'suspend'           => '0',
                'delete'            => '0',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 0,
                'sequence'          => 4,
                'menu_type'         => 4,
                'icon'              => 'edit_document',
                'shortname'         => 'Administrative Tools',
                'caption'           => 'ADMINISTRATIVE TOOLS',
                'action'            => null,
                'show'              => '1',
                'create'            => '1',
                'update'            => '1',
                'suspend'           => '1',
                'delete'            => '1',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 11,
                'sequence'          => 3,
                'menu_type'         => 5,
                'icon'              => 'groups',
                'shortname'         => 'Group Roles',
                'caption'           => 'GROUP ROLES',
                'action'            => '/administrative-tools/group-roles',
                'show'              => '0',
                'create'            => '0',
                'update'            => '0',
                'suspend'           => '0',
                'delete'            => '0',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 11,
                'sequence'          => 4,
                'menu_type'         => 5,
                'icon'              => 'people',
                'shortname'         => 'User Management',
                'caption'           => 'USER MANAGEMENT',
                'action'            => '/administrative-tools/user-management',
                'show'              => '0',
                'create'            => '0',
                'update'            => '0',
                'suspend'           => '0',
                'delete'            => '0',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 11,
                'sequence'          => 5,
                'menu_type'         => 5,
                'icon'              => 'settings',
                'shortname'         => 'Application Properties',
                'caption'           => 'APPLICATION PROPERTIES',
                'action'            => '/administrative-tools/application-properties',
                'show'              => '0',
                'create'            => '1',
                'update'            => '0',
                'suspend'           => '1',
                'delete'            => '1',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 11,
                'sequence'          => 6,
                'menu_type'         => 5,
                'icon'              => 'event_repeat',
                'shortname'         => 'Log Activities',
                'caption'           => 'LOG ACTIVITIES',
                'action'            => '/administrative-tools/log-activities',
                'show'              => '0',
                'create'            => '1',
                'update'            => '1',
                'suspend'           => '1',
                'delete'            => '0',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 11,
                'sequence'          => 1,
                'menu_type'         => 5,
                'icon'              => 'table_rows',
                'shortname'         => 'Master Data',
                'caption'           => 'MASTER DATA',
                'action'            => '/administrative-tools/master-data',
                'show'              => '0',
                'create'            => '0',
                'update'            => '0',
                'suspend'           => '0',
                'delete'            => '0',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ],[
                'refid'             => 11,
                'sequence'          => 2,
                'menu_type'         => 5,
                'icon'              => 'view_list',
                'shortname'         => 'Master Data Detail',
                'caption'           => 'MASTER DATA DETAIL',
                'action'            => '/administrative-tools/master-data-detail',
                'show'              => '0',
                'create'            => '0',
                'update'            => '0',
                'suspend'           => '0',
                'delete'            => '0',
                'showMenu'          => '0',
                'status'            => '0',
                'created_by'        => 1,
                'created_at'        => now(),
            ]
        ]);
    }
    
}
