# This is a basic workflow to help you get started with Actions
name: cd-dev-jobposting
# Controls when the action will run, Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
# A workflow run is nade up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: deploy using ssh
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 1945
          script: |
          cd /var/www/html/dev-jobposting
          git add .
          git commit -m "Update"
          git pull origin --rebase
          git pull origin main
          php artisan migrate:fresh --seed
          npm run build
          php artisan route:cache
          php artisan cache:clear
          php artisan view:clear
          php artisan config:clear
          php artisan config:cache
          php artisan optimize:clear
          chown -R apache:apache /var/www/html/dev-jobposting
          chown -R apache:apache /var/www/html/dev-jobposting/public/
          chown -R apache:apache /var/www/html/dev-jobposting/storage/
          chown -R apache:apache /var/www/html/dev-jobposting/bootstrap/
          chown -R apache:apache /var/www/html/dev-jobposting/vendor/
          chmod -R 777 /var/www/html/dev-jobposting/vendor/
          chmod -R 777 /var/www/html/dev-jobposting/storage/
          chmod -R 777 /var/www/html/dev-jobposting/bootstrap/
          service nginx restart
