on:
  push:
    branches:
      - main

jobs:
  build-js-production:
    name: Build JavaScript/CSS for Production Server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - name: NPM Build
        run: |
          #npm i
          #npm run build --if-present
      - name: Put built assets in Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: public
          retention-days: 3
  deploy-production:
    name: Deploy Project to Production Server
    runs-on: ubuntu-latest
    needs: [ build-js-production ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - name: Fetch built assets from Artifacts
        uses: actions/download-artifact@v1
        with:
          name: assets
          path: public
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.2'
          extension-csv: mbstring, bcmath
      - name: Composer install
        run: /usr/local/bin/composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: deploy using ssh
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 1945
          script: |
            sudo su
            cd /var/www/html/dev-jobposting
            git add .
            git commit -m "Update"
            git pull origin --rebase
            git pull origin main
            #php artisan storage:link
            php artisan migrate
            #npm i
            #npm run build
            php artisan route:cache
            php artisan cache:clear
            php artisan view:clear
            php artisan config:clear
            php artisan config:cache
            php artisan optimize:clear
            chown -R apache:apache /var/www/html/dev-jobposting
            chown -R apache:apache /var/www/html/dev-jobposting/public/
            chown -R apache:apache /var/www/html/dev-jobposting/storage/
            chown -R apache:apache /var/www/html/dev-jobposting/bootstrap/
            chown -R apache:apache /var/www/html/dev-jobposting/vendor/
            chmod -R 777 /var/www/html/dev-jobposting/vendor/
            chmod -R 777 /var/www/html/dev-jobposting/storage/
            chmod -R 777 /var/www/html/dev-jobposting/bootstrap/
            service nginx restart
